DOMAIN_NAME: facebookfracking.watch
SERVER_NAME: qdlp5gmjof.execute-api.us-west-2.amazonaws.com
ZONE_ID: Z028948124VAGPSA4M4T9
CERTIFICATE_ARN: arn:aws:acm:us-east-1:140410646227:certificate/c01f996d-c37e-4642-988f-c3acc7d42e08
ENVIRONMENT: prod
REGION: us-west-2
BUCKET_NAME: 140410646227-facebook-drilling-watch-prod